### ISSUE TITLE
Add e2e test

### ISSUE THREAD

**Issue by jcchavezs** [fionera/haproxy-go#1]
When writing a connector to a service, it is usually a good practice to provide a e2e test that verify the integration works as expected and avoid regressions (better to run a check on CI). This is haproxy instance running and a sample component running and returning an expected output. This also helps to triage issues

**Comment by fionera** [comment]
Yep I do have a local test env but just dont know how I really want to structure this repo as I want all haproxy protos together since they do share encoding etc. Will probably reset master and migrate everything thats not spop (e.g. the acutally developed code) into a develop branch. Do you already have a good testing config you could contribute?

**Comment by jcchavezs** [comment]
Not a strong user of haproxy but I would recommend you go step by step. I
would just add a folder `e2e` with all configs relative to the test and
then from that start realising what is part of the core and what isn't.

**Comment by fionera** [comment]
Added a e2e test chain that starts haproxy and validated that it works with a simple acl
